### ISSUE TITLE
Improve README to illustrate clearer usage of the -a/-e options

### ISSUE THREAD

**Issue by david-homley** [brightsparklabs/appcli#26]
The README.md is not clear on how to use the -a/-e options, e.g. there are no clear examples documenting their expected usage.

The 'help' message could also be a bit more descriptive and clear in stating the expected format of the supplied arguments as well.

**Comment by al-jeyapal** [comment]
Specifically, you need to supply values in the format `HELLO=/path/to/hello`. Our help text should just explain that better. Especially in relation to `-a` since the key (left hand side) will be used as an environment variable name, and needs to conform to certain conventions (cannot contain hyphens, etc)

**Comment by thomas-anderson-bsl** [comment]
Resolved by #45
