### ISSUE TITLE
Have a dictionary store within ctx.obj (appcli.model.cli_context)

### ISSUE THREAD

**Issue by benjamin-wiffen** [brightsparklabs/appcli#266]
Sometimes we may need to include some additional data along with a `ctx` object.
As `ctx.obj` is our appcli object `appcli.model.cli_context`, it makes sense to include a dictionary within this object that we can put data into:
```
ctx.obj.put("my_object", MyObject())
ctx.obj.get("my_object")
```

**Comment by thomas-anderson-bsl** [comment]
@benjamin-wiffen What's the context for wanting a dictionary store? It sounds like a solution to a problem you're having, but that isn't described here.

This ticket is describing an implementation detail (i.e. add a dict and two methods to a particular internal class) instead of an 'issue' you're raising with APPCLI itself. Part of the problem with just prescribing a solution is that it hides the motivation for the change, and gives no flexibility or context for why the change is being made. It could be that there's another approach that may be more reasonable to fix whatever issue you're having, or perhaps the ticket isn't required at all.

**Comment by benjamin-wiffen** [comment]
In our monitoring stack: https://bitbucket.org/brightsparklabs/monitoring-stack/src/develop/ there is a Kibana connection object that is passed along with the cli_context object. This is currently stored with the `__dict__` dunder method of the Click ctx object. Creating a custom datastore in the appcli cli_context means we could store multiple the additional data without using `__dict__`.

**Comment by thomas-anderson-bsl** [comment]
I've talked directly with Ben about the use-case in monitoring-stack. Essentially for custom commands, the following code is executed:

```
ctx.__dict__["kibana_request"] = KibanaRequest(ctx)
```

This stores a custom object in the ctx object by overriding `__dict__` dunder attribute. This seems like really bad practice, as it's overriding part of a dunder method and could have unintended consequences. This just isn't the right way to pass variables around.

I think that what the monitoring-stack is doing is not correct, and doesn't require a change to appcli. In the monitoring stack, wherever it calls `ctx.kibana_request.request(` could be replaced with `KibanaRequest(ctx).request(`, and you no longer need to push attributes into `__dict__`. This removes the change from appcli which is not required, and wouldn't be used.

**Comment by thomas-anderson-bsl** [comment]
@benjamin-wiffen has also raised that we would be instantiating the `KibanaRequest(ctx)` object potentially many times over. In this case, we should instantiate it once and pass it around (using function parameters would be a good use case in the code base).

**Comment by benjamin-wiffen** [comment]
The problems this would have fixed have been addressed directly in monitoring-stack.
See https://bitbucket.org/brightsparklabs/monitoring-stack/commits/dfed6b902a21fcc942dacc85b72580dc34ec216d
